#!/usr/bin/perl

# The first line (above) is the Shebang, telling the system to use the Perl interpreter.
# IMPORTANT: The path to the Perl interpreter must be correct for your system.

use strict;
use warnings;

# --- CGI HEADER ---
# This is CRITICAL. The Content-type header must be printed first,
# followed by two newline characters (\n\n) to signal the end of the headers.
print "Content-type: text/html\n\n";

# --- HTML CONTENT ---
print "<html>\n";
print "<head>\n";
print "    <title>Perl CGI Test</title>\n";
print "</head>\n";
print "<body>\n";
print "    <h1>Hello, World!</h1>\n";
print "    <p>This page was generated by the Perl script: <code>hello.pl</code></p>\n";
print "</body>\n";
print "</html>\n";

exit;
